[tool.black]
line-length = 88
target-version = ['py39']

[tool.flake8]
max-line-length = 88
extend-ignore = [
    "E203",
    "W503",
]


[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_ignores = true
# mypy_path = src
